language: node_js

dist: trusty

os:
  - linux
  - osx

node_js:
  - 8
cache:
  directories:
    - "node_modules"

before_install:
  - git clean -xdff
  - npm i -g yarn

install:
  - yarn

script:
  - yarn lint

sudo: false
